In [1]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

In [3]:
import os

os.chdir('..') # Change to parent directory
cwd = os.getcwd() # Get current working directory
print(cwd)

C:\Users\templ\OneDrive\Desktop\AI\Hackathon\Amazon

In [5]:
# Read the dataset using Dask
dataset = pd.read_csv('dataset/universal_train.csv', on_bad_lines='skip', encoding='utf-8', engine='python')
# dataset =  dataset.sample(n=20000)

In [6]:
dataset.columns

Index(['Unnamed: 0', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       'PRODUCT_TYPE_ID', 'PRODUCT_LENGTH', 'PRODUCT_LENGTH_NONORM'],
      dtype='object')

In [7]:
dataset = dataset.drop(['Unnamed: 0','PRODUCT_LENGTH', 'PRODUCT_LENGTH_NONORM'],axis=1)

In [8]:
dataset

,0,1,2,3,4,5,6,7,8,9,10,PRODUCT_TYPE_ID
0,0.033740,0.053593,0.119451,-0.002144,-0.023888,-0.009354,-0.013213,-0.011067,-0.052480,-0.005460,-0.048928,-0.592630
1,0.021798,0.017311,-0.010543,0.044631,-0.013809,0.007838,-0.019112,0.012684,-0.002693,0.000218,0.007681,-0.314022
2,0.021713,0.010882,0.012488,-0.015654,0.011082,0.004986,-0.017478,-0.003682,-0.005930,-0.000192,-0.005423,0.891683
3,0.041322,0.102819,-0.029833,0.067824,0.101342,-0.023887,0.054705,-0.005680,-0.031651,-0.000720,-0.008348,-0.253258
4,0.001786,0.004194,0.001742,-0.000216,-0.001976,0.006235,-0.000607,0.000235,-0.002081,0.000451,0.008637,0.532392
...,...,...,...,...,...,...,...,...,...,...,...,...
2249693,0.019544,0.061277,-0.024850,0.036257,0.073269,-0.017734,0.047925,0.000918,0.012451,-0.000118,-0.004641,-0.249980
2249694,0.020147,0.015623,0.021427,-0.000404,0.003816,0.009220,-0.025823,-0.002782,-0.011322,0.000861,0.017507,-0.148118
2249695,0.063208,0.032880,0.119688,0.024788,-0.071651,-0.024792,0.045420,-0.009083,0.004295,-0.002458,-0.022181,-0.611792
2249696,0.033887,0.054742,0.086165,-0.033040,-0.014690,-0.016088,0.023324,0.032273,0.099026,-0.000348,-0.022752,-0.859387
2249697,0.005274,0.007339,0.013561,-0.001855,0.002032,0.004187,-0.014808,0.000081,-0.009082,-0.000322,-0.002877,0.848820

In [9]:
KNN = pd.read_csv('dataset/trial.csv', on_bad_lines='skip', encoding='utf-8', engine='python')

In [10]:
KNN

        PRODUCT_ID  PRODUCT_LENGTH
0           604373      585.528138
1          1729783      439.886896
2          1871949      475.161660
3          1107571      532.994656
4           624253      613.436173
...            ...             ...
734731      921419      357.816225
734732     2456362      568.192956
734733      841529      337.537282
734734     1190194      416.640906
734735     1040810      589.765561

[734736 rows x 2 columns]

In [11]:
dataset['PRODUCT_LENGTH'] = KNN['PRODUCT_LENGTH']

In [12]:
dataset

,0,1,2,3,4,5,6,7,8,9,10,PRODUCT_TYPE_ID,PRODUCT_LENGTH
0,0.033740,0.053593,0.119451,-0.002144,-0.023888,-0.009354,-0.013213,-0.011067,-0.052480,-0.005460,-0.048928,-0.592630,585.528138
1,0.021798,0.017311,-0.010543,0.044631,-0.013809,0.007838,-0.019112,0.012684,-0.002693,0.000218,0.007681,-0.314022,439.886896
2,0.021713,0.010882,0.012488,-0.015654,0.011082,0.004986,-0.017478,-0.003682,-0.005930,-0.000192,-0.005423,0.891683,475.161660
3,0.041322,0.102819,-0.029833,0.067824,0.101342,-0.023887,0.054705,-0.005680,-0.031651,-0.000720,-0.008348,-0.253258,532.994656
4,0.001786,0.004194,0.001742,-0.000216,-0.001976,0.006235,-0.000607,0.000235,-0.002081,0.000451,0.008637,0.532392,613.436173
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2249693,0.019544,0.061277,-0.024850,0.036257,0.073269,-0.017734,0.047925,0.000918,0.012451,-0.000118,-0.004641,-0.249980,NaN
2249694,0.020147,0.015623,0.021427,-0.000404,0.003816,0.009220,-0.025823,-0.002782,-0.011322,0.000861,0.017507,-0.148118,NaN
2249695,0.063208,0.032880,0.119688,0.024788,-0.071651,-0.024792,0.045420,-0.009083,0.004295,-0.002458,-0.022181,-0.611792,NaN
2249696,0.033887,0.054742,0.086165,-0.033040,-0.014690,-0.016088,0.023324,0.032273,0.099026,-0.000348,-0.022752,-0.859387,NaN
2249697,0.005274,0.007339,0.013561,-0.001855,0.002032,0.004187,-0.014808,0.000081,-0.009082,-0.000322,-0.002877,0.848820,NaN

In [19]:
dataset.interpolate(method ='linear', limit_direction ='forward')

,0,1,2,3,4,5,6,7,8,9,10,PRODUCT_TYPE_ID,PRODUCT_LENGTH
0,0.033740,0.053593,0.119451,-0.002144,-0.023888,-0.009354,-0.013213,-0.011067,-0.052480,-0.005460,-0.048928,-0.592630,585.528138
1,0.021798,0.017311,-0.010543,0.044631,-0.013809,0.007838,-0.019112,0.012684,-0.002693,0.000218,0.007681,-0.314022,439.886896
2,0.021713,0.010882,0.012488,-0.015654,0.011082,0.004986,-0.017478,-0.003682,-0.005930,-0.000192,-0.005423,0.891683,475.161660
3,0.041322,0.102819,-0.029833,0.067824,0.101342,-0.023887,0.054705,-0.005680,-0.031651,-0.000720,-0.008348,-0.253258,532.994656
4,0.001786,0.004194,0.001742,-0.000216,-0.001976,0.006235,-0.000607,0.000235,-0.002081,0.000451,0.008637,0.532392,613.436173
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2249693,0.019544,0.061277,-0.024850,0.036257,0.073269,-0.017734,0.047925,0.000918,0.012451,-0.000118,-0.004641,-0.249980,589.765561
2249694,0.020147,0.015623,0.021427,-0.000404,0.003816,0.009220,-0.025823,-0.002782,-0.011322,0.000861,0.017507,-0.148118,589.765561
2249695,0.063208,0.032880,0.119688,0.024788,-0.071651,-0.024792,0.045420,-0.009083,0.004295,-0.002458,-0.022181,-0.611792,589.765561
2249696,0.033887,0.054742,0.086165,-0.033040,-0.014690,-0.016088,0.023324,0.032273,0.099026,-0.000348,-0.022752,-0.859387,589.765561
2249697,0.005274,0.007339,0.013561,-0.001855,0.002032,0.004187,-0.014808,0.000081,-0.009082,-0.000322,-0.002877,0.848820,589.765561

In [25]:
dataset.to_csv("interpolatedKNNtraining.csv", index = False)

In [22]:
train = pd.read_csv('dataset/train.csv', on_bad_lines='skip', encoding='utf-8', engine='python')

In [23]:
train

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,PRODUCT_LENGTH
0,1925202,ArtzFolio Tulip Flowers Blackout Curtain for D...,[LUXURIOUS & APPEALING: Beautiful custom-made ...,NaN,1650,2125.980000
1,2673191,Marks & Spencer Girls' Pyjama Sets T86_2561C_N...,"[Harry Potter Hedwig Pyjamas (6-16 Yrs),100% c...",NaN,2755,393.700000
2,2765088,PRIKNIK Horn Red Electric Air Horn Compressor ...,"[Loud Dual Tone Trumpet Horn, Compatible With ...","Specifications: Color: Red, Material: Aluminiu...",7537,748.031495
3,1594019,ALISHAH Women's Cotton Ankle Length Leggings C...,[Made By 95%cotton and 5% Lycra which gives yo...,AISHAH Women's Lycra Cotton Ankel Leggings. Br...,2996,787.401574
4,283658,The United Empire Loyalists: A Chronicle of th...,NaN,NaN,6112,598.424000
...,...,...,...,...,...,...
2249693,2422167,Nike Women's As W Ny Df Swsh Hn Kh Bra (CZ7610...,Material : Polyester,NaN,3009,1181.100000
2249694,2766635,"(3PCS) Goose Game Cute Cartoon Enamel Pins, Fu...",[❤ [Inspiration] Inspired by the Untitled Goos...,<p><b>[Brand]: </b>XVIEONR</p> <p><br></p> <p>...,3413,125.984252
2249695,1987786,Kangroo Sweep Movement Printed Wooden Wall Clo...,"[Dial size: 12 inches in diameter,Big, clear r...",Wall Clocks Are Very Attractive In Looks And E...,1574,1200.000000
2249696,1165754,Electro Voice EKX-BRKT15 | Wall Mount Bracket ...,NaN,NaN,592,2900.000000
2249697,1072666,Skyjacker C7360SP Component Box For PN[C7360PK...,"[Component Box For PN[C7360PK],4 in. Lift,Incl...",Skyjacker C7360SP Component Box For PN[C7360PK...,7367,2000.000000

In [26]:
dftrain = dataset

In [27]:
dftrain.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       'PRODUCT_TYPE_ID', 'PRODUCT_LENGTH'],
      dtype='object')

In [28]:
dftrain = dftrain.drop(['PRODUCT_LENGTH'],axis=1)

In [29]:
dftrain.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       'PRODUCT_TYPE_ID'],
      dtype='object')

In [31]:
dftrain = dftrain.drop(['PRODUCT_TYPE_ID'],axis=1)

KeyError: "['PRODUCT_TYPE_ID'] not found in axis"

In [32]:
dftrain.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='object')

In [34]:
dftrain['PRODUCT_LENGTH'] = train['PRODUCT_TYPE_ID']

In [37]:
dftrain.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       'PRODUCT_LENGTH'],
      dtype='object')

In [38]:
dftrain = dftrain.drop(['PRODUCT_LENGTH'],axis=1)

In [39]:
dftrain['PRODUCT_TYPE_ID'] = train['PRODUCT_TYPE_ID']

In [40]:
dftrain.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       'PRODUCT_TYPE_ID'],
      dtype='object')

In [41]:
dftrain['PRODUCT_LENGTH'] = train['PRODUCT_LENGTH']

In [42]:
dftrain

,0,1,2,3,4,5,6,7,8,9,10,PRODUCT_TYPE_ID,PRODUCT_LENGTH
0,0.033740,0.053593,0.119451,-0.002144,-0.023888,-0.009354,-0.013213,-0.011067,-0.052480,-0.005460,-0.048928,1650,2125.980000
1,0.021798,0.017311,-0.010543,0.044631,-0.013809,0.007838,-0.019112,0.012684,-0.002693,0.000218,0.007681,2755,393.700000
2,0.021713,0.010882,0.012488,-0.015654,0.011082,0.004986,-0.017478,-0.003682,-0.005930,-0.000192,-0.005423,7537,748.031495
3,0.041322,0.102819,-0.029833,0.067824,0.101342,-0.023887,0.054705,-0.005680,-0.031651,-0.000720,-0.008348,2996,787.401574
4,0.001786,0.004194,0.001742,-0.000216,-0.001976,0.006235,-0.000607,0.000235,-0.002081,0.000451,0.008637,6112,598.424000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2249693,0.019544,0.061277,-0.024850,0.036257,0.073269,-0.017734,0.047925,0.000918,0.012451,-0.000118,-0.004641,3009,1181.100000
2249694,0.020147,0.015623,0.021427,-0.000404,0.003816,0.009220,-0.025823,-0.002782,-0.011322,0.000861,0.017507,3413,125.984252
2249695,0.063208,0.032880,0.119688,0.024788,-0.071651,-0.024792,0.045420,-0.009083,0.004295,-0.002458,-0.022181,1574,1200.000000
2249696,0.033887,0.054742,0.086165,-0.033040,-0.014690,-0.016088,0.023324,0.032273,0.099026,-0.000348,-0.022752,592,2900.000000
2249697,0.005274,0.007339,0.013561,-0.001855,0.002032,0.004187,-0.014808,0.000081,-0.009082,-0.000322,-0.002877,7367,2000.000000

In [43]:
dftrain.to_csv("trainfinal.csv", index = False)